services:
  horeca:
    image: nextapp
    build: .
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    deploy:
      resources:
        limits:
          memory: 256M
          
networks:
  horeca_api_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450