services:
  horeca:
    image: nextapp
    build: .
    environment:
      - NEXT_PUBLIC_APP_BASE_API=http://95.163.222.187:3001
      - NEXT_PUBLIC_APP_WS_CHATS_API=ws://95.163.222.187:4001/chats
    ports:
      - "80:3000"
    deploy:
      resources:
        limits:
          memory: 256M
